// src/settings/components/Header.tsx
import { FC } from "react";
import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import { LinkContainer } from "react-router-bootstrap";

const Header: FC = () => {
  return (
    <header className="header">
      <Navbar bg="light" expand="lg">
        <Container>
          <Navbar.Brand href="#home">
            <img src="icon128.png" width="48" />
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="me-auto">
              <LinkContainer to="/">
                <Nav.Link>Settings</Nav.Link>
              </LinkContainer>
              <LinkContainer to="/insights">
                <Nav.Link>Insights</Nav.Link>
              </LinkContainer>
              <LinkContainer to="/about">
                <Nav.Link>About</Nav.Link>
              </LinkContainer>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </header>
  );
};

export default Header;

// src/options/components/Header.svelte
<script lang="ts">
  import {
    Collapse,
    Container,
    Navbar,
    NavbarBrand,
    NavbarToggler,
    NavItem,
    Nav,
    NavLink,
  } from "@sveltestrap/sveltestrap";

  import { link } from "svelte-spa-router";
  import active from "svelte-spa-router/active";
</script>

<Navbar class="header" color="light" light container="md">
  <NavbarBrand href="/">
    <img src="/assets/icon128.png" width="48" alt="" />
  </NavbarBrand>
  <Nav>
    <NavItem>
      <a href="/" class="nav-link" use:link use:active>Settings</a>
    </NavItem>
    <NavItem>
      <a href="/insights/" class="nav-link" use:link use:active>Insights</a>
    </NavItem>
    <NavItem>
        <a href="/about/" class="nav-link" use:link use:active>About</a>
      </NavItem>
  </Nav>
</Navbar>
