// src/options/components/SaveForm.svelte
<script lang="ts">
  import { Button, Input } from "@sveltestrap/sveltestrap";
  import { createForm } from "felte";
  import { storage } from "../../stores/storage";
  import { saveToFile } from "../../internal/fs";

  type WarningsExport = Record<
    string,
    { type: string; selection?: string; clipboard?: string }[]
  >;

  const stripClipboardData = (logState: WarningsExport) => {
    const data = { ...logState };
    Object.keys(data).forEach((key) => {
      data[key] = data[key].map(({ type }) => ({ type }));
    });
    return data;
  };

  const { form } = createForm({
    initialValues: {
      includeClipboard: false,
    },
    async onSubmit(values) {
      const now = Date.now();
      const dataToSave = values.includeClipboard
        ? $storage.warnings
        : stripClipboardData($storage.warnings);
      saveToFile(
        JSON.stringify(dataToSave),
        `copyguard-log-${now}.json`,
        "application/json",
      );
    },
  });
</script>

<form use:form>
  <Button class="save-to-file-btn" color="primary">Save to file</Button>
  <Input
    name="includeClipboard"
    type="switch"
    inline
    label="include clipboard data"
  />
</form>

// src/settings/components/SaveForm.tsx
import { useForm, Controller } from "react-hook-form";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import { saveToFile } from "../../utils/fs";

const stripClipboardData = (logState) => {
  const data = { ...logState };
  Object.keys(data).forEach((key) => {
    data[key] = data[key].map(({ type }) => ({ type }));
  });
  return data;
};

const SaveForm = ({ logState }) => {
  const { control, handleSubmit } = useForm({
    defaultValues: {
      includeClipboard: "",
    },
  });

  const onSubmit = (saveSettings) => {
    const dataToSave = saveSettings.includeClipboard ? logState : stripClipboardData(logState);
    saveToFile(JSON.stringify(dataToSave), "copyguard-log.json", "application/json");
  };

  return (
    <Form onSubmit={handleSubmit(onSubmit)}>
      <p>
        <Button type="submit">Save to file</Button>

        <Controller
          name="includeClipboard"
          control={control}
          render={({ field }) => (
            <Form.Check
              {...field}
              inline
              type="switch"
              name="include-clipboard"
              label="include clipboard data"
              className="push-right"
            />
          )}
        />
      </p>
    </Form>
  );
};

export default SaveForm;
